CRUD for users added
96mickey/typescriptserver pull request #1
Opened 2019-05-09 04:28 UTC by 96mickey

Server files added.

2019-05-14 12:53 UTC, samarpan-b requested changes

2019-05-14 12:53 UTC, samarpan-b commented on app/user/userModel.ts
> +  save() {
why this ?

2019-05-14 12:53 UTC, samarpan-b commented on app/user/userControlModel.ts
> +export class UserControlModel {
rename this to data-functions

2019-05-14 12:53 UTC, samarpan-b commented on app/types.ts
> +export interface UserValidation {
why is this copied ?

2019-05-14 12:53 UTC, samarpan-b commented on app/types.ts
> +  role?: number;
use enum

2019-05-14 12:53 UTC, samarpan-b commented on app/user/userModel.ts
> +export class UserModel {
use either model or interface

2019-05-14 12:53 UTC, samarpan-b commented on app/user/controllers.ts
> +  getSingleUser = (req: Request, res: Response) => {
use void return type

2019-05-14 12:53 UTC, samarpan-b commented on app/user/utils.ts
> +export const getUsersFromFile = (cb: any) => {
make this more generic

2019-05-14 12:53 UTC, samarpan-b commented on app/user/utils.ts
> +export const ValidateReq = (
make this more generic

2019-05-15 05:27 UTC, 96mickey commented on app/user/userModel.ts
> +  save() {
this is to push data in json file.

2019-05-15 08:19 UTC, samarpan-b requested changes

2019-05-15 08:19 UTC, samarpan-b commented on app/utils.ts
> +export const getUsersFromFile = (path: any, cb: any) => {
getDataFromFile

2019-05-15 08:19 UTC, samarpan-b commented on app/user/model.ts
> +      fs.writeFile(pathfunction("user.json"), JSON.stringify(users), err => {
move this to utils

2019-05-16 13:27 UTC, samarpan-b requested changes
Add comments to each function and class in the code

2019-05-16 13:27 UTC, samarpan-b commented on app/user/validation-schema.ts
> +  email = {
add type as string. type is a mandatory attribute

2019-05-16 13:27 UTC, samarpan-b commented on app/utils.ts
> +export const ValidateReq = (
if this is user specific move it inside user folder

2019-05-16 13:27 UTC, samarpan-b commented on app/utils.ts
> +import fs from "fs";
Move this file to core/utils

2019-05-20 06:01 UTC, samarpan-b commented on app/user/controller.ts
> +   * @param {object} req.body is required and should contain data to create a new user. it holds various fields like first name, last name, email etc.
fn description missing

2019-05-20 07:09 UTC, samarpan-b approved these changes

2019-05-20 07:09 UTC, merged